server:
  port: 8282
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: consumer-v1
  kafka:
    bootstrap-servers:
      - localhost:9092
  cloud:
    schema:
      avro:
        dynamicSchemaGenerationEnabled: true #Then, we just need to enable dynamic Avro schema generation. Once you do it, Spring Cloud Stream automatically generates and sends schema to the schema registry before sending a message to a Kafka topic.
    schemaRegistryClient:
      endpoint: http://localhost:8081/
    stream:
      default:
        content-type: application/*+avro
      source: person
      bindings:
        person-in-0:
          destination: person-topic
          content-type: application/*+avro
          group: '${spring.application.name}'