apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: fabricio211/producer:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 800Mi
              cpu: "300m"
            limits:
              memory: 800Mi
              cpu: "300m"
          livenessProbe:
            httpGet:
              port: 9090
              scheme: HTTP
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 40
            timeoutSeconds: 2
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: producer
    spring-boot: "true"
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: producer