server:
  port: 9090
spring:
  application:
    name: producer
  kafka:
    bootstrap-servers:
      - kafka:9092
  cloud:
    stream:
      source: person
      bindings:
        person-out-0:
          destination: person
          contentType: application/json
          group: '${spring.application.name}'